name       : xfsprogs
version    : 6.2.0
release    : 21
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/xfsprogs-6.2.0.tar.xz : d67dcba5a28e0904b60886b6e5f752bc7c9c3a5c7096153855b5adca9db86c51
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
homepage   : https://xfs.wiki.kernel.org/
summary    : XFS User Tools
description: |
    XFS combines advanced journaling technology with full 64-bit addressing and scalable structures and algorithms. This combination delivers the most scalable high-performance filesystem ever conceived.
component  : system.utils
patterns   :
    - devel : /usr/share/man/man3
builddeps  :
    - pkgconfig(inih)
    - pkgconfig(liburcu)
    - libunistring-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-merged-usr-tree-layout.patch
    %configure
build      : |
    %make
install    : |
    %make_install install-dev
