name       : xfsprogs
version    : 5.12.0
release    : 14
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/xfsprogs-5.12.0.tar.xz : bec44445cf18f49e63971d4f27dc4e90a17b118b852714a1104b621ea30e3507
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
summary    : XFS User Tools
description: |
    XFS combines advanced journaling technology with full 64-bit addressing and scalable structures and algorithms. This combination delivers the most scalable high-performance filesystem ever conceived.
component  : system.utils
patterns   :
    - devel : /usr/share/man/man3
builddeps  :
    - pkgconfig(inih)
    - libunistring-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-merged-usr-tree-layout.patch
    %configure
build      : |
    %make
install    : |
    # Yes it actually needs -j1. Will fail to install headers otherwise.
    %make_install -j1 install-dev
