name       : xfsprogs
version    : 4.17.0
release    : 7
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/xfsprogs-4.17.0.tar.xz : f53f5169cb98cfca471ddea30092738c427ba284c5356e01b45dd1ae3b297e0d
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
summary    : XFS User Tools
component  : system.utils
patterns   :
    - devel : /usr/share/man/man3
description: |
    XFS combines advanced journaling technology with full 64-bit addressing and scalable structures and algorithms. This combination delivers the most scalable high-performance filesystem ever conceived.
builddeps  :
    - libunistring-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-merged-usr-tree-layout.patch
    %configure
build      : |
    %make
install    : |
    %make_install install-dev
