name       : xfsprogs
version    : 4.8.0
release    : 2
source     :
    - https://cdn.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/xfsprogs-4.8.0.tar.xz : 82ce9cb3a55f4e208e8fe3471ff0aff0602b8300f3e50bdf05cc7e11549686f9
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : XFS User Tools
component  : system.utils
description: |
    XFS combines advanced journaling technology with full 64-bit addressing and scalable structures and algorithms. This combination delivers the most scalable high-performance filesystem ever conceived.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # Empty directory
    rm -r %installroot%/usr/include/xfs
