name       : xfsprogs
version    : 4.11.0
release    : 3
source     :
    - https://cdn.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/xfsprogs-4.11.0.tar.xz : c3a6d87b564d7738243c507df82276bed982265e345363a95f2c764e8a5f5bb2
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : XFS User Tools
component  : system.utils
description: |
    XFS combines advanced journaling technology with full 64-bit addressing and scalable structures and algorithms. This combination delivers the most scalable high-performance filesystem ever conceived.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # Empty directory
    rm -r %installroot%/usr/include/xfs
