name       : xfsprogs
version    : 4.2.0
release    : 1
source     :
    - ftp://oss.sgi.com/projects/xfs/cmd_tars/xfsprogs-4.2.0.tar.gz : 3deab1ad0f4635e54053aa45add27bd48cd87a188c16ac60f4789e01730e5260
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : XFS User Tools
description: |
    XFS combines advanced journaling technology with full 64-bit addressing and scalable structures and algorithms. This combination delivers the most scalable high-performance filesystem ever conceived.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # Empty directory
    rm -r %installroot%/usr/include/xfs
