name       : xfsprogs
version    : 4.12.0
release    : 5
source     :
    - https://cdn.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/xfsprogs-4.12.0.tar.xz : b330ad8d737f4152ae511580102e2fc49212bb51dfb4b614084344abae46d0df
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : XFS User Tools
component  : system.utils
patterns   :
    - devel: /usr/share/man/man3
description: |
    XFS combines advanced journaling technology with full 64-bit addressing and scalable structures and algorithms. This combination delivers the most scalable high-performance filesystem ever conceived.
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-merged-usr-tree-layout.patch
    %configure
build      : |
    %make
install    : |
    %make_install install-dev
