name       : xfsprogs
version    : 4.16.1
release    : 6
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/xfsprogs-4.16.1.tar.xz : 3d5c2da46112b86cbd967fee43cea731d38a1b2aaf601b57674ed34e808652df
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
summary    : XFS User Tools
component  : system.utils
patterns   :
    - devel : /usr/share/man/man3
description: |
    XFS combines advanced journaling technology with full 64-bit addressing and scalable structures and algorithms. This combination delivers the most scalable high-performance filesystem ever conceived.
builddeps  :
    - libunistring-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-merged-usr-tree-layout.patch
    %configure
build      : |
    %make
install    : |
    %make_install install-dev
